"""car fk update

Revision ID: 232451e79349
Revises: 309a0124ea56
Create Date: 2024-04-17 23:54:20.138842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232451e79349'
down_revision: Union[str, None] = '309a0124ea56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trips_car_id_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_car_id_fkey', 'trips', 'users', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
