"""avatar can be null

Revision ID: 309a0124ea56
Revises: eb80ff2a3be7
Create Date: 2024-04-17 15:07:43.785128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309a0124ea56'
down_revision: Union[str, None] = 'eb80ff2a3be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    op.drop_column('users', 'avatar_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
