"""rename mode to model

Revision ID: 373971f7405d
Revises: 432e24301725
Create Date: 2024-04-17 13:59:27.798622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373971f7405d'
down_revision: Union[str, None] = '432e24301725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model', sa.String(), nullable=False))
    op.drop_column('cars', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cars', 'model')
    # ### end Alembic commands ###
