"""added icons

Revision ID: 58189ea191c8
Revises: 232451e79349
Create Date: 2024-04-30 21:49:03.436589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58189ea191c8'
down_revision: Union[str, None] = '232451e79349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cars', sa.Column('image0_id', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('image1_id', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('image2_id', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('image3_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cars', 'images', ['image1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cars', 'images', ['image0_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cars', 'images', ['image3_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cars', 'images', ['image2_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cars', 'photo')
    op.add_column('chat_messages', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'image_path')
    op.add_column('reviews', sa.Column('image_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'images', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'image_id')
    op.add_column('chat_messages', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'image_id')
    op.add_column('cars', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'image3_id')
    op.drop_column('cars', 'image2_id')
    op.drop_column('cars', 'image1_id')
    op.drop_column('cars', 'image0_id')
    op.drop_table('images')
    # ### end Alembic commands ###
