"""added popultaion column

Revision ID: 959b09f500da
Revises: 5ba64bcb5473
Create Date: 2024-06-19 14:45:04.851955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959b09f500da'
down_revision: Union[str, None] = '5ba64bcb5473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('population', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'population')
    # ### end Alembic commands ###
