"""init

Revision ID: 95b90c300951
Revises: cf082a3be69c
Create Date: 2024-05-15 22:06:40.122361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b90c300951'
down_revision: Union[str, None] = 'cf082a3be69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('available_seats', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.String(), nullable=False))
    op.add_column('users', sa.Column('musicPreferences', sa.String(), nullable=True))
    op.add_column('users', sa.Column('info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'info')
    op.drop_column('users', 'musicPreferences')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'email')
    op.drop_column('users', 'surname')
    op.drop_column('trips', 'available_seats')
    # ### end Alembic commands ###
