"""nullablr images in car

Revision ID: 99274c8f9730
Revises: 1f6308df7d9b
Create Date: 2024-05-29 11:43:18.238036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99274c8f9730'
down_revision: Union[str, None] = '1f6308df7d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'image0_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'image0_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
