"""nullable avatar

Revision ID: cf082a3be69c
Revises: 58189ea191c8
Create Date: 2024-05-15 20:13:50.361977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf082a3be69c'
down_revision: Union[str, None] = '58189ea191c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
