name: Deploy buy runner

on:
  push:
    branches: [ "master", "dev"]

jobs:
  deploy:
    runs-on: self-hosted # Запускаем на раннере, который настроили до этого.
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose build
        run: docker compose build
      - name: docker compose up
        run: docker compose up -d
